version: "3.5"
services:
  mongodb:
    image: mongo:3.6.8
    ports:
      - 27017:27017
    networks:
      - dev
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dev
  webserver:
    build: .
    environment:
        MONGODB_URI: "${MONGODB_URI}"
        REDIS_URI: "${REDIS_URI}"
        MONGODB_HOST: "mongodb"
    ports:
      - 3000:3000
    networks:
      - dev

networks:
  dev:
    driver: bridge